### ISSUE TITLE
30min task dont show two_col  on timeline view

### ISSUE THREAD

**Issue by yamatatsu** [sudachiapp/forum#19]
かとぺーーーーー！！

i set two task on same time.
and, one of task (that 30min task) is not with two_col.
if this task set 1hour, show two_col as usual

[![Screenshot from Gyazo](https://gyazo.com/0dd11273af1c274551e38cca0c0034f1/raw)](https://gyazo.com/0dd11273af1c274551e38cca0c0034f1)

**Comment by kato1628** [comment]
@yamatatsu I have fixed this issue in [v0.2.3](https://github.com/sudachiapp/releases/releases/tag/v0.2.3) :)
