### ISSUE TITLE
Scrollbars are visible on scrollable area.

### ISSUE THREAD

**Issue by yohawing** [sudachiapp/forum#29]
App version: v0.3.0
Your Environment: macOS Sierra 10.13.1 (with mouse logicool M170)

preview:
<img width="1490" alt="screen shot 2018-02-08 at 13 14 54" src="https://user-images.githubusercontent.com/1789072/35955339-25efc49e-0cd2-11e8-979b-f1ee30be90f0.png">

**Comment by kato1628** [comment]
@yohawing 
Thank you for the report and the capture image. I'm gonna look into this issue.

**Comment by kato1628** [comment]
@yohawing 
I investigated this issue and found that macOS has a settings of scroll bars.
It may be possible to make the scroll bars display only when scrolling:

1. Launch System Preferences from the  Apple menu
2. Click on the “General” settings panel
3. Look for ‘Show scroll bars’ and select the radio box next to “When scrolling”
4. Close out of System Preferences when finished

I was wondering if you might be able to try this way :)

**Comment by kato1628** [comment]
@yohawing If the bug wouldn't be fixed by the above workaround, please reopen this issue:)
